version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/your-app
    mode: 755  # Critical for permissions
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: root